Installing Spring XD using Ambari
=================================

These instructions apply to an installation using link:http://pivotalhd.docs.pivotal.io/docs/install-ambari.html[Pivotal Ambari]. For instructions to set up a single-node VM using Pivotal Ambari and Pivotal HD 3.0 see link:InstallingPHDwithAmbari.asciidoc[Installing Pivotal HD 3.0 on single-node VM using Ambari]

IMPORTANT: This is still a work-in-progress and these packages have not yet been released.

==== Copying and installing Spring XD files

Copy the `SPRINGXD.tar` file to the YUM repository machine. I'm copying the file to a directory named `/staging`.

Then unpack the `SPRINGXD.tar` file and create a symbolic link for YUM repository using:

[source]
----
# tar -xvf /staging/SPRINGXD.tar -C /staging/
# ln -s /staging/SPRINGXD /var/www/html/SPRINGXD
----

Alternatively you can unpack the archive directly to the `/var/www/html/` directory:

[source]
----
# tar -xvf /staging/SPRINGXD.tar -C /var/www/html/
----


Copy the `springxd-plugin-phd-1.0-1.noarch.rpm` file to the Ambari server machine. I'm copying the file to a directory named `/staging`. 

Then install the Ambari plugin by installing the RPM package:

[source]
----
# rpm -ivh /staging/springxd-plugin-phd-1.0-1.noarch.rpm
----

We now need to restart the Ambari server to pick up this new plugin:

[source]
----
# ambari-server restart
----

==== Install a Transport (Redis)

We need to have a transport installed. Spring XD currently supports Redis and Kafka for the Ambari installation. I'll use Redis since that seems simpler.

You can build Redis from source or you can use RPMs that are available from the link:https://fedoraproject.org/wiki/EPEL[EPEL] project. I'm using the RPM packages. Source is available from the link:http://redis.io/download[Redis download] page. Redis source will also be installed in the `/opt/pivotal/spring-xd/redis` directory.

We need to add a Fedora YUM repo for Redis and then install it:

[source]
----
# wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
# sudo rpm -Uvh epel-release-6*.rpm
# sudo yum -y install redis
# chkconfig redis on
----

Modify `\etc\redis.conf`, comment out the `bind` setting:

[source]
----
# If you want you can bind a single interface, if the bind option is not
# specified all the interfaces will listen for incoming connections.
#
#bind 127.0.0.1
----

After this we can start Redis:

[source]
----
# sudo service redis start
----

We can now test Redis by using:

[source]
----
# redis-cli -h `hostname` ping
PONG
----

==== Install Spring XD using Ambari UI

Open the Ambari UI and log in as `admin`. From the Dashboard click on "Actions + Add Service" on the left hand side under the list of services. Check "Spring XD" and click `Next ->`. Both master, slave and client will be on the same host since we only have one. Just click `Next ->` a couple of times.

Under "Customize Services" we need to make a few changes:

For "Advanced springxd-site" enter the following:

[width="80%",cols="1m,2m",frame="topbot"]
|=====================================
|hsql.server.port            | 9101
|server.port                 | 9393
|spring.redis.host           | <hostname where redis is running>
|spring.redis.port           | 6379
|xd.messagebus.kafka.brokers | 
|xd.transport                | redis
|=====================================

Then click `Next ->`.

Review the configuration and then click `Deploy ->`.

==== Test the Spring XD installation

To start the XD Shell enter the following command:

[source]
----
xd-shell
----

Now, from the XD Shell run the following commands:

[source]
----
xd:>script --file /etc/springxd/conf/xd-shell.init
xd:>stream create tictoc --definition "time | hdfs" --deploy
----

To check that the stream works run the following commands:

[source]
----
xd:>hadoop fs ls /xd
Found 1 items
drwxrwxrwx   - spring-xd hdfs          0 2015-05-28 16:03 /xd/tictoc
----

Now, destroy the stream and display the output:

[source]
----
xd:>stream destroy tictoc
xd:>hadoop fs cat /xd/tictoc/*
2015-05-28 16:04:37
2015-05-28 16:04:38
2015-05-28 16:04:39
2015-05-28 16:04:40
2015-05-28 16:04:41
2015-05-28 16:04:42
2015-05-28 16:04:43
2015-05-28 16:04:44
2015-05-28 16:04:45
2015-05-28 16:04:46
2015-05-28 16:04:47
2015-05-28 16:04:48
2015-05-28 16:04:49
2015-05-28 16:04:50
2015-05-28 16:04:51
2015-05-28 16:04:52
2015-05-28 16:04:53
2015-05-28 16:04:54
----

NOTE: [green yellow-background big]*That's it -- have fun!*